### ISSUE TITLE
Group buffs are gone

### ISSUE THREAD

**Issue by 2ndHouse** [TekNoLogic/Cork#110]
Many of the group buffs are now gone in Legion in seems, so they could safely be removed from the various class modules.

**Comment by 2ndHouse** [comment]
Many stances have been removed also it seems.

**Comment by tekkub** [comment]
I've been fixing these as I come across them, but I don't play all the classes out there (I haaaate playing melee).  If you run across any specific ones I've missed, please open up an issue for it.
