### ISSUE TITLE
Dark Intent is gone

### ISSUE THREAD

**Issue by pontusm** [TekNoLogic/Cork#113]
Getting this error when I login with my Warlock. I believe it is because Dark Intent is now gone.

Message: Interface\AddOns\Cork\templates\RaidBuffer.lua:26: attempt to concatenate local 'spellname' (a nil value)
Time: 08/19/16 20:27:51
Count: 1
Stack: [C]: ?
Interface\AddOns\Cork\templates\RaidBuffer.lua:26: in function `GenerateRaidBuffer'
Interface\AddOns\Cork\modules\Warlock.lua:13: in main chunk

**Comment by tekkub** [comment]
I believe I caught this one in a recent update.
