### ISSUE TITLE
Death Knight Presences

### ISSUE THREAD

**Issue by xephonia** [TekNoLogic/Cork#63]
Not sure if this is in scope of your addon, but I'd love to have Cork nag me if I'm in my Blood spec but not in Blood Presence. The same could be done for Frost spec, although that's a little more subjective since it's currently recommended that you be in Unholy presence for Frost spec, but some people may still want Frost.

Anyhow, it'd be nice to have the option to toggle presence warnings on or off. I added the following to my own DeathKnight.lua file and it works perfectly for me. Love to see it added to the real release going forward.

-- Blood Presence
local spellname, _, icon = GetSpellInfo(48263)
Cork:GenerateSelfBuffer(spellname, icon)

-- Unholy Presence
local spellname, _, icon = GetSpellInfo(48265)
Cork:GenerateSelfBuffer(spellname, icon)

-- Frost Presence
local spellname, _, icon = GetSpellInfo(48266)
Cork:GenerateSelfBuffer(spellname, icon)

**Comment by tekkub** [comment]
Closing as stale.  Please reopen if this is still an issue.
