### ISSUE TITLE
Lua error after using Earth Shield + respeccing

### ISSUE THREAD

**Issue by ckaotik** [TekNoLogic/Cork#89]
When I cast Earth Shield on my resto shaman Cork remembers the target - perfect.
However, when I respec to elemental, Cork can no longer find info on Earth Shield as that spell is no longer known for me and spams errors :(

    [14:41:16] Interface\AddOns\Cork\templates\LastBuffedBuffer.lua:48: attempt to perform arithmetic on local 'start' (a nil value)
    (tail call): ?
    Interface\AddOns\Cork\templates\LastBuffedBuffer.lua:48: in function <Interface\AddOns\Cork\templates\LastBuffedBuffer.lua:24>
    Interface\AddOns\Cork\templates\LastBuffedBuffer.lua:54: in function <Interface\AddOns\Cork\templates\LastBuffedBuffer.lua:53>
    [string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
    [C]: ?
    [string "safecall Dispatcher[1]"]:13: in function `?'
    ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
    ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by tekkub** [comment]
Closing as stale.  Please reopen if this is still an issue.
